- CHANGELOG.md
- Dockerfile
- camply/__init__.py
- camply/config/api_config.py
- camply/config/cli_config.py
- camply/notifications/email_notifications.py
- camply/utils/camply_cli.py
- pyproject.toml
- setup.py
- Filter out `Checkout-Only` campsites by excluding `Open` availability status
- No longer trapping all errors with `exit(0)`
- Email notifications now attempt login at start, to throw errors early.
[0.1.2]: https://github.com/juftin/camply/compare/v0.1.1...v0.1.2
> camply 0.1.2

- camply/providers/recreation_dot_gov/campsite_search.py
Fix parsing facilities responses without `FACILITY_ADDRESS` or `CAMPGROUND_RECREATION_AREA` by adding `except KeyError`
Sample facility response from 89898:
```
{'FacilityID': '', 'LegacyFacilityID': '', 'OrgFacilityID': '', 'ParentOrgID': '', 'ParentRecAreaID': '', 'FacilityName': '', 'FacilityDescription': '', 'FacilityTypeDescription': '', 'FacilityUseFeeDescription': '', 'FacilityDirections': '', 'FacilityPhone': '', 'FacilityEmail': '', 'FacilityReservationURL': '', 'FacilityMapURL': '', 'FacilityAdaAccess': '', 'GEOJSON': {'TYPE': '', 'COORDINATES': None}, 'FacilityLongitude': 0, 'FacilityLatitude': 0, 'Keywords': '', 'StayLimit': '', 'Reservable': False, 'Enabled': False, 'LastUpdatedDate': ''}
```
> Fix parsing facilities responses

- .github/workflows/docs.yml
- camply/_version.py
- requirements.txt
This fixes #90 by declaring a minimum `rich` version
> Fixes #90 Add minimum rich version to requirements.txt

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- README.md
- camply/_version.py
- camply/cli.py
- camply/config/logging_config.py
- camply/providers/recreation_dot_gov/recdotgov_provider.py
- camply/search/search_recreationdotgov.py
- docs/source/cli.rst
- tests/command_line_test.sh
This pull request resolves https://github.com/juftin/camply/issues/100
When multiple campsites are searched the `_get_equipment_and_attributes` function was returning a pandas Series instead of a list of dictionaries. 
This PR also adds the ability to pass `--debug` to camply to see the local variables returned in traceback as well as to force DEBUG logging.
> Multiple Campsites Bugfix

- .github/workflows/publish.yaml
- .github/workflows/release.yaml
This PR fixes an issue where Releases can't be created due to branch protections
This PR will publish the release that https://github.com/juftin/camply/pull/110 was supposed to.
Nope 🙈
> Bugfix: Release Token

- .github/workflows/release.yaml
This updates the current release process to run on merges to main, instead of on PR close. This allows Github Actions to use my personal secrets instead of the forked secrets of another user's repo
Kinda
> BugFix: Contributor Release Permissions

- .github/workflows/release.yaml
- .github/workflows/tests.yaml
- camply/notifications/slack.py
This updates the current release process to run on merges to main, instead of on PR close. This allows Github Actions to use my personal secrets instead of the forked secrets of another user's repo.
This Also fixes the missing releases. 
Kinda
> BugFix: Missing Release

- README.md
Click doesn't support comma-separated value for multiple options:
https://click.palletsprojects.com/en/8.1.x/options/#multiple-options
When trying to use a comma-separated list of values for `--notifications`, camply crashes.
Also note that I haven't made many/any contributions via Github before, so if I'm not following best practices please educate me!
> Update documentation on how to specify multiple notification providers

- Dockerfile
- README.md
- camply/notifications/base_notifications.py
- camply/notifications/email_notifications.py
- camply/notifications/multi_provider_notifications.py
- camply/notifications/pushbullet.py
- camply/notifications/pushover.py
- camply/notifications/silent_notifications.py
- camply/notifications/slack.py
- camply/notifications/telegram.py
- camply/notifications/twilio.py
- pyproject.toml
This PR cleans up the notification Providers. It converst the ClassMethod / StaticMethod AbstractMethods into InstanceMethods, removes the per-class __repr__, and adds a little camply branding to SMS text messages. It 
I ran this locally on multiple providers.
> Notification Cleanup

- Dockerfile
- poetry.lock
- pyproject.toml
- tox.ini
This PR uses the Poetry Lock File when installing dependencies into the Docker image. It also installs Shell Completion and removes the testing "dev" extras.
Yesh
> Docker: Use Lock File

- .github/workflows/docs.yaml
- camply/cli.py
[//]: # Changed triple quotes to single quotes for help text in `--equipment-id` in `cli.py`. This now matches other help texts spanning multiple lines, and should fix the issue with compiling the options into a table.
[//]: # The options in the  [CLI documentation](https://juftin.com/camply/cli/#documentation) under "Campsites" does not compile correctly: from `--equipment-id` onwards, the table seems to break. This change hopefully fixes that issue and puts everything into their appropriate table.
[//]: # Unfortunately, I couldn't quite figure out how to compile the documentation on my own system, so that hasn't been tested yet. Happy to do so if the maintainers give me a pointer for how to compile the documentation. :) 
- [x ] I've read the [contributing …
> 📝 CLI Documentation Formatting

- .github/workflows/lint.yaml
- .pre-commit-config.yaml
- camply/cli.py
- camply/config/api_config.py
- camply/containers/api_responses.py
- camply/providers/__init__.py
- camply/providers/base_provider.py
- camply/providers/recreation_dot_gov/recdotgov_camps.py
- camply/providers/recreation_dot_gov/recdotgov_provider.py
- camply/providers/recreation_dot_gov/recdotgov_tours.py
- camply/search/__init__.py
- camply/search/base_search.py
- camply/search/search_recreationdotgov.py
- tox.ini
A tour facility is currently modeled as a campground and each individual tour is a campsite. User interface was not updated yet but the logic does the work as expected.
I'm not an regular user of Python typing so I probably erased some typing info or didn't use it correctly here and there.
Fixes #74.
[//]: # (Please include a summary of the changes and a link/description of the related issue.)
[//]: # (Please also include relevant motivation and context.)
> ✨ RecDotGov Tours + Timed Entry

- camply/notifications/silent_notifications.py
It currently breaks a message into characters and puts them in a bullet list, specifically for notifier.send_message() calls in base_search.py.
[//]: # (Please include a summary of the changes and a link/description of the related issue.)
[//]: # (Please also include relevant motivation and context.)
> 🐛 SilentNotifications.send_message BugFix

- camply/providers/going_to_camp/going_to_camp_provider.py
- docs/providers.md
Oroville, Hamilton, and Yukon recreation areas appear to no longer be GoingToCamp customers and their sites are down.
Yes -- a campground list was performed on all remaining GTC recreation areas.
> :bug: Remove defunct GTC recreation areas

- camply/providers/going_to_camp/going_to_camp_provider.py
- docs/providers.md
- tests/cli/cassettes/test_goingtocamp_search_nova_scotia.yaml
- tests/cli/test_going_to_camp.py
Implements Nova Scotia Parks via GoingToCamp
Closes #267
> ✨ Nova Scotia Parks

- README.md
- camply/config/file_config.py
- camply/config/notification_config.py
- camply/containers/data_containers.py
- camply/notifications/base_notifications.py
- camply/notifications/multi_provider_notifications.py
- camply/notifications/webhook.py
- docs/command_line_usage.md
- docs/how_to_run.md
- docs/index.md
Send notifications to a webhook endpoint
Resolves #295
> ✨ webhook notifications

- docs/examples/example_search.yaml
Clarify comment for --weekends flag in example yaml config
The --weekends flag is intended to mean "weekends only" and will exclude weekdays from the search
[//]: # (Please include a summary of the changes and a link/description of the related issue.)
[//]: # (Please also include relevant motivation and context.)
No. But it's just a minor clarification to the documentation.
> Clarify weekends usage in example_search.yaml

- camply/providers/usedirect/usedirect.py
- tests/debug_camply.py
> 🐛 usedirect startdate

- camply/providers/going_to_camp/going_to_camp_provider.py
This PR addresses the issue reported in #328, where API requests from camply to the GoingToCamp WA site were being blocked by DataDome, resulting in a 403 captcha error.
Upon examining the network requests on the GoingToCamp WA site, I observed that their API calls included a large set of HTTP headers, including those related to DataDome's bot protection. To isolate the essential headers required to prevent the API request from being rejected, I just copied the request and removed headers one by one. I identified that retaining only the `User-Agent` and `Accept-Language` headers circumvented the issue.
Further investigation into the [DataDome Request Validation API](https://docs.datadome.co/reference/validate-request) revealed that the Accept-Language header is among the top headers …
> 🐛 add accept-language header to goingtocamp requests

- camply/providers/xanterra/yellowstone_lodging.py
> 🐛 yellowstone availability response empty

- camply/config/notification_config.py
- camply/notifications/pushover.py
- camply/search/base_search.py
There is an issue where an improperly set up camply config in a constantly restarting docker container sends notifications all day. In the case of pushover, a process sent ~4,500 notifications today (and I believe they're error messages). This PR only emits the "last gasp" error notification if the search has run at least once. 
It also replaces the built-in Pushover token - which resolves an issue for the month of May where the token limit is reached.
> 🐛 persistent error notifications

- camply/search/search_yellowstone.py
```shell
camply campsites --provider yellowstone --start-date 2025-07-04 --end-date 2025-07-08 --notifications silent --equipment RV 40 --campground YLYC:RV --nights 4
```
The issues I'm having is that even with the 4 consecutive nights flag, I'm getting dates for July 1 - 4, not 4 - 7.
> 🐛 yellowstone date filtering

- camply/search/search_recreationdotgov.py
Documentation Update - This PR addresses issue #363 by improving docstring/naming convention consistency for various methods in `search_recreationdotgov.py`.
Cleaned up docstrings of: 
- `_get_searchable_campgrounds`
- `_get_campgrounds_by_campground_id`
- `_get_campgrounds_by_campsite_id`
- `_get_campgrounds_by_recreation_area_id`
Changed return variable name in `_get_campgrounds_by_recreation_area_id` from `campgrounds` to `facilities` to be consistent with previous methods naming convention.
> :memo: Documentation Update - search_recreationdotgov.py methods
