README.md
scripts/check-yellowstone.sh
scripts/docker-entrypoint.sh
scripts/find_availabilities.py
yellowstone_availability/check_yellowstone.py

- Update to the `YellowstoneLodging` class to use initialized properties, instead of just passing them around vie classmethods
- Documentation Clarification

YellowstoneLodging Class Update + Bash Logging

---

.github/ISSUE_TEMPLATE/bug_report.md
CHANGELOG.md
Dockerfile
README.md
camply/config/api_config.py
camply/config/cli_config.py
pyproject.toml
setup.py

- Updating Badges
- Excluded `Lottery` sites from being returned
[0.1.1]: https://github.com/juftin/camply/compare/v0.1.0...v0.1.1

camply 0.1.1

---

.github/ISSUE_TEMPLATE/config.yml
.github/workflows/camply-publishing.yml
.github/workflows/docker-image-ci.yml
CHANGELOG.md
Dockerfile
SECURITY.md
camply/__init__.py
camply/config/cli_config.py
camply/notifications/email_notifications.py
camply/providers/recreation_dot_gov/campsite_search.py
camply/search/search_recreationdotgov.py
camply/utils/camply_cli.py
pyproject.toml

- CI/CD for publishing camply to Docker Hub and PyPi
- Addressed situations where campsites without addresses information were throwing a KeyError. (big
thanks to @ grantland)
- This resolution presents an
interesting [discussion](https://github.com/juftin/camply/pull/14#issuecomment-848302948)
on whether campsites that have `Enabled` and `Reservable` = `False` should be searchable.
- Empty Email notifications issue resolved
[0.1.3]: https://github.com/juftin/camply/compare/v0.1.2...v0.1.3

camply 0.1.3

---

.github/workflows/pytest.yml
CHANGELOG.md
Dockerfile
README.md
camply/__init__.py
camply/config/__init__.py
camply/config/api_config.py
camply/config/cli_config.py
camply/config/data_columns.py
camply/containers.py
camply/notifications/email_notifications.py
camply/notifications/pushbullet.py
camply/notifications/pushover.py
camply/notifications/silent_notifications.py
camply/providers/__init__.py
camply/providers/recreation_dot_gov/campsite_search.py
camply/providers/xanterra/yellowstone_lodging.py
camply/search/base_search.py
camply/search/search_recreationdotgov.py
camply/search/search_yellowstone.py
camply/utils/camply_cli.py
camply/utils/yaml_utils.py
docs/README.docker.md
docs/examples/docker-compose.yml
docs/examples/example_search.yml
pyproject.toml
tests/search_providers/test_recdotgov_search.py

- Ability to search for campsites by number of consecutive night stays.
[0.1.6]: https://github.com/juftin/camply/compare/v0.1.5...v0.1.6

camply - 0.1.6

---

MANIFEST.in
camply/__main__.py
camply/_version.py
setup.py
tox.ini

This creates an object oriented link to the requirements.txt file - this ensures dependencies are installed

BugFix: Dependency Installation

---

camply/_version.py
camply/config/api_config.py

New Status, NYR. It presumably stands for "Not Yet Released".

New Unreservable Status: NYR

---

.github/workflows/lint.yml
camply/_version.py
pyproject.toml

Creating all the needed poetry config in the main branch for the new poetry-related feature - this config won't be used until the `pyproject.toml` is set to use the poetry backend

Poetry Seed File

---

camply/_version.py

This pushes a missed release - I need to fix some stuff so contributors can merge their branches directly into main.

Missed Release

---

.github/workflows/docker.yaml
.github/workflows/release.yaml
.github/workflows/tests.yaml
docs/source/conf.py

Latest Cookiecutter Updates

---

.github/ISSUE_TEMPLATE/bug_report.md
README.md
camply/notifications/base_notifications.py
docs/examples/example_search.yaml
pyproject.toml
tests/command_line_test.sh
tests/yaml/example_campsite_search.yaml
tests/yaml/example_search.yaml

This fixes issues where campsites don't have permitted equipment (https://github.com/juftin/camply/issues/122)
Yeah, locally 🤙

BugFix: No Equipment to Iterate On

---

camply/containers/api_responses.py
camply/providers/recreation_dot_gov/recdotgov_provider.py
tests/command_line_test.sh

Some campgrounds don't have information about their parent Recreation Area - this PR will fall back on the Organization in those cases.
```
poetry run camply --debug campsites \
--start-date 2022-10-01 \
--end-date 2022-10-02 \
--campground 234779
[2022-09-26 13:01:15] CAMPLY   camply, the campsite finder ⛺️
[2022-09-26 13:01:15] DEBUG    Setting up camply debugging
[2022-09-26 13:01:15] DEBUG    Camply Version: 0.6.1
[2022-09-26 13:01:15] DEBUG    Python Version: 3.9.5
[2022-09-26 13:01:15] DEBUG    Platform: darwin
[2022-09-26 13:01:15] INFO     1 booking nights selected for search, ranging from 2022-10-01 to 2022-10-01
[2022-09-26 13:01:15] DEBUG    Starting new HTTPS connection (1): ridb.recreation.gov:443
[2022-09-26 13:01:17] DEBUG    https://ridb.recreation.gov:443 "GET …
```

Campground Without Recreation Area

---

.github/workflows/tests.yaml
Dockerfile
README.md
camply/cli.py
camply/config/logging_config.py
camply/containers/api_responses.py
camply/containers/base_container.py
camply/containers/data_containers.py
camply/providers/recreation_dot_gov/recdotgov_provider.py
camply/search/base_search.py
camply/search/search_recreationdotgov.py
camply/search/search_yellowstone.py
camply/utils/yaml_utils.py
docs/examples/example_search.yaml
docs/source/cli.md
poetry.lock
pyproject.toml
tests/command_line_test.sh
tox.ini

This Release PR Implements Three New Features:
- #133 
- #134 
- #135
Yeppers!

camply 0.7.0

---

README.md
docs/source/index.md

This PR adds a link to the new Camply Discord server
Nope

Discord Server

---

.github/workflows/release.yaml
README.md
docs/source/index.md

Small Release: Discord Server + Dependency Update

Release 0.7.1

---

Dockerfile

Recreates the HOME env var in docker
Closes #169 

🐛 Docker Home Directory

---

.github/workflows/release.yaml

🐛 CI/CD Triggers

---

.github/helpers/version_check.py
.github/workflows/lint.yaml
.pre-commit-config.yaml
camply/cli.py
camply/config/file_config.py
camply/notifications/base_notifications.py
camply/notifications/email_notifications.py
camply/notifications/twilio.py
camply/providers/base_provider.py
camply/providers/going_to_camp/going_to_camp_provider.py
camply/providers/recreation_dot_gov/recdotgov_camps.py
camply/providers/recreation_dot_gov/recdotgov_provider.py
camply/providers/recreation_dot_gov/recdotgov_tours.py
camply/providers/xanterra/yellowstone_lodging.py
camply/search/base_search.py
camply/search/search_going_to_camp.py
camply/search/search_recreationdotgov.py
camply/search/search_yellowstone.py
camply/utils/api_utils.py
camply/utils/configure_camply.py
camply/utils/yaml_utils.py
poetry.lock
pyproject.toml
tests/conftest.py
tox.ini

🐛 Lint with Ruff

---

camply/search/base_search.py

Fixes https://github.com/juftin/camply/issues/192
Yes!

🐛 Pandas Timestamp BugFix

---

camply/containers/data_containers.py
camply/notifications/silent_notifications.py
camply/providers/__init__.py
camply/search/base_search.py
camply/search/search_going_to_camp.py

Fixes https://github.com/juftin/camply/issues/199
This PR makes a search's dates dynamic based on the current date of the search. This fix handles issues where searches are run over multiple months.
Yes - but trying to test this with something like [time-machine](https://github.com/adamchainz/time-machine) was tough and I didn't go for that.

🐛  Dynamic Search Dates

---

README.md
camply/cli.py
camply/notifications/silent_notifications.py
camply/search/__init__.py
camply/search/search_going_to_camp.py
camply/search/search_recreationdotgov.py
camply/search/search_yellowstone.py
docs/command_line_usage.md
docs/index.md

This PR closes https://github.com/juftin/camply/issues/201
List Providers from the CLI

✨ List Providers

---

README.md
camply/cli.py
camply/config/logging_config.py
camply/search/base_search.py
docs/command_line_usage.md
docs/dependencies.md
docs/index.md
docs/installation.md
mkdocs.yml
poetry.lock
pyproject.toml
tox.ini

Rich Click and Sensible Defaults

✨ CLI Improvements

---

camply/providers/going_to_camp/going_to_camp_provider.py
docs/providers.md

This PR adds additional GTC recreation areas, partially fixes https://github.com/juftin/camply/issues/177

Add more GoingToCamp recreation areas

---

README.md
camply/cli.py
camply/containers/examples.py
camply/providers/base_provider.py
camply/search/base_search.py
camply/search/search_going_to_camp.py
camply/search/search_recreationdotgov.py
camply/search/search_yellowstone.py
camply/utils/general_utils.py
camply/utils/yaml_utils.py
docs/command_line_usage.md
docs/examples/example_search.yaml
docs/index.md
tests/cli/cassettes/test_search_specific_weekdays.yaml
tests/cli/cassettes/test_search_specific_weekdays_yaml.yaml
tests/cli/test_campsites.py
tests/yaml/weekday_search.yaml

[✨ Search By Weekday](https://github.com/juftin/camply/pull/229/commits/28f579f65686b66b691e439ae858739546f23027)
[✨ test-notifications](https://github.com/juftin/camply/pull/229/commits/5f0864169bb8afec8a2d2775c3df637594ae1953)
Closes #230

✨ Search By Weekday

---

camply/config/api_config.py

[//]: # (Please include a summary of the changes and a link/description of the related issue.)
[//]: # (Please also include relevant motivation and context.)
Fixes #243 
Note: This doesn’t implement the more robust solution I suggested, but this at least unblocked me for now.
Haven’t thoroughly tested this, just made the change locally and it removed the false positives. I don’t have access to my usual dev environment, so I can’t run the proper dev tools unfortunately.

Add Closed to list of unavailable statuses

---

camply/cli.py
camply/notifications/multi_provider_notifications.py
camply/search/base_search.py

Notifier sends out a "last gasp" before camply exits
Closes https://github.com/juftin/camply/issues/255

✨ notifier last gasp

---

.gitignore
.pre-commit-config.yaml
camply/__init__.py
camply/cli.py
camply/config/api_config.py
camply/config/file_config.py
camply/containers/usedirect.py
camply/providers/__init__.py
camply/providers/going_to_camp/__init__.py
camply/providers/going_to_camp/going_to_camp_provider.py
camply/providers/reserve_california/__init__.py
camply/providers/usedirect/__init__.py
camply/providers/usedirect/usedirect.py
camply/providers/usedirect/variations.py
camply/providers/xanterra/yellowstone_lodging.py
camply/search/__init__.py
camply/search/search_going_to_camp.py
camply/search/search_usedirect.py
camply/search/search_yellowstone.py
tests/search_providers/test_reserve_california.py

This PR Implements an `AbstractBaseClass` for `UseDirect` providers (there are lots coming in a subsequent PR). It also streamlines the provider "registration" process and changes the name of a couple provider classes to do this.

✨ UseDirect + Provider Registry

---

camply/providers/going_to_camp/going_to_camp_provider.py

Resolves https://github.com/juftin/camply/issues/261
```python
❯ hatch run python -m camply campgrounds --provider goingtocamp --rec-area 3 --campground -2147483572
[2023-06-06 00:16:38] CAMPLY   camply, the campsite finder ⛺️
[2023-06-06 00:16:38] INFO     Using Camply Provider: "GoingToCamp"
[2023-06-06 00:16:38] INFO     Retrieving Facility Information for Recreation Area ID: `3`.
[2023-06-06 00:16:39] INFO     1 Matching Campgrounds Found
[2023-06-06 00:16:39] INFO     ⛰  Washington State Parks, Washington (#3) - 🏕  Penrose Point State Park (#-2147483572)
[2023-06-06 00:16:39] CAMPLY   Exiting camply 👋
```

🐛 GoingToCamp Filtering

---

camply/containers/usedirect.py

Addresses https://github.com/juftin/camply/issues/263. This PR makes almost all UseDirect API fields optional which should stop errors from popping up across its providers.

🐛 UseDirect API Validation

---

camply/config/data_columns.py
camply/containers/data_containers.py
camply/notifications/base_notifications.py
camply/notifications/webhook.py
camply/providers/recreation_dot_gov/recdotgov_camps.py
camply/providers/usedirect/usedirect.py

Adds geolocation to webhook responses - also resolves a utf-8 webhook encoding issue.
Resolves #300 
Resolves #302

✨ campsite geolocation
